server.servlet.context-path=/api/v1

spring.application.name=messaging
app.db.url=jdbc:mariadb://db:3306/messaging_db
app.db.username=root
app.db.password=epai123
app.jwt.secretkey=Une clé secrète, très secrète, extrêmement secrète.
